language: python
python: 2.7
sudo: required
services:
  - docker

env:
  - CHECK=jslint4java
  - CHECK=pyflakes
  - CHECK=i18ndude
  - CHECK=zptlint
  - PLONE=4
  - PLONE=5

install:
  - export GIT_OWNER=${TRAVIS_REPO_SLUG%/*}
  - export GIT_NAME=${TRAVIS_REPO_SLUG#*/}
  - export GIT_CHANGE_ID=${TRAVIS_PULL_REQUEST#false}
  - export GIT_SRC=https://github.com/${TRAVIS_REPO_SLUG}.git

jobs:
  include:
    - stage: code
      env:
        - PLONE=all
      script:
        - docker run -i --rm -e GIT_BRANCH=$TRAVIS_BRANCH -e GIT_SRC=$GIT_SRC -e GIT_NAME=$GIT_NAME -e GIT_CHANGE_ID=$GIT_CHANGE_ID eeacms/$CHECK

    - stage: test
      env:
        - CHECK=plone-test
      script:
        - docker run -i --rm -e GIT_BRANCH="$TRAVIS_BRANCH" -e ADDONS="$GIT_NAME" -e DEVELOP="src/$GIT_NAME" -e GIT_CHANGE_ID="$GIT_CHANGE_ID" eeacms/$CHECK:$PLONE -s $GIT_NAME
